# Generated by Django 5.2.11 on 2026-04-21 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('semana_referencia', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras_principais', to='core.cliente')),
                ('clientes', models.ManyToManyField(blank=True, related_name='obras', to='core.cliente')),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ImagemObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='obras/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('atualizacao_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='core.atualizacaoobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.obra')),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('PROJETO', 'Projeto'), ('ORCAMENTO', 'Orçamento'), ('CONTRATO', 'Contrato'), ('NOTA_FISCAL', 'Nota fiscal'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/arquivos/')),
                ('descricao', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.obra')),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
        migrations.AddField(
            model_name='atualizacaoobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='core.obra'),
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arquivo_pdf', models.FileField(upload_to='orcamentos/pdfs/')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('mensagem_cliente', models.TextField(blank=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.obra')),
            ],
            options={
                'ordering': ['-data_emissao'],
                'constraints': [models.UniqueConstraint(fields=('obra', 'versao'), name='orcamento_obra_versao_unica')],
            },
        ),
    ]
