# Generated by Django 5.2.11 on 2026-05-15 04:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=core.models.documento_upload_path),
        ),
        migrations.AlterField(
            model_name='imagemobra',
            name='imagem',
            field=models.ImageField(upload_to=core.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='arquivo_pdf',
            field=models.FileField(upload_to=core.models.orcamento_upload_path),
        ),
    ]
